In [22]:
from pathlib import Path
from spikeinterface.extractors.extractor_classes import (
    OpenEphysBinaryRecordingExtractor,
)
import tetrode_analyses as ta
import numpy as np

In [23]:
ACQ_DIR = Path("/Volumes/neuropixel_archive/tetrode_data/2026-05-19_18-09-51")
ta.print_session_tree(ACQ_DIR)

Session: /Volumes/neuropixel_archive/tetrode_data/2026-05-19_18-09-51
  Record Node 101 (binary)  [record_node_index=0]
    experiment1  [experiment_index=0]
      recording1  [recording_index=0]
        Stream 0: acquisition_board  — 64 ch, 1,815,085 samples @ 30000.0 Hz, 60.503 s
        Stream 1: memory_usage  — 1 ch, 6,050 samples @ 100.0 Hz, 60.500 s
      recording2  [recording_index=1]
        Stream 0: acquisition_board  — 64 ch, 1,807,473 samples @ 30000.0 Hz, 60.249 s
        Stream 1: memory_usage  — 1 ch, 6,025 samples @ 100.0 Hz, 60.250 s
      recording3  [recording_index=2]
        Stream 0: acquisition_board  — 64 ch, 1,788,934 samples @ 30000.0 Hz, 59.631 s
        Stream 1: memory_usage  — 1 ch, 5,963 samples @ 100.0 Hz, 59.630 s


In [24]:
da = ta.open_tetrode_dataarray(ACQ_DIR, layout="2d_flat_index")
da

<xarray.DataArray 'mul-a2ac8d337a55c82f113bec84cb152b81' (time: 1815085,
                                                          channel: 64)> Size: 465MB
dask.array<mul, shape=(1815085, 64), dtype=float32, chunksize=(1048576, 64), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) float64 15MB 18.67 18.67 18.67 18.67 ... 79.17 79.17 79.17
  * channel  (channel) <U4 1kB 'CH40' 'CH38' 'CH36' ... 'CH28' 'CH30' 'CH32'
    tetrode  (channel) <U4 1kB 'TT1' 'TT1' 'TT1' 'TT1' ... 'TT16' 'TT16' 'TT16'
Attributes:
    fs:       30000.0
    units:    microvolts

In [25]:
ta.open_tetrode_dataarray(ACQ_DIR, layout="2d_multi_index")

<xarray.DataArray 'mul-a2ac8d337a55c82f113bec84cb152b81' (time: 1815085,
                                                          electrode: 64)> Size: 465MB
dask.array<mul, shape=(1815085, 64), dtype=float32, chunksize=(1048576, 64), chunktype=numpy.ndarray>
Coordinates:
  * time       (time) float64 15MB 18.67 18.67 18.67 18.67 ... 79.17 79.17 79.17
  * electrode  (electrode) object 512B MultiIndex
  * tetrode    (electrode) object 512B 'TT1' 'TT1' 'TT1' ... 'TT16' 'TT16'
  * channel    (electrode) object 512B 'CH40' 'CH38' 'CH36' ... 'CH30' 'CH32'
Attributes:
    fs:       30000.0
    units:    microvolts

In [26]:
ta.open_tetrode_dataarray(ACQ_DIR, layout="3d")

<xarray.DataArray 'reshape-9cafe5bb772a53fb7a707640d803aeae' (time: 1815085,
                                                              tetrode: 16,
                                                              channel: 4)> Size: 465MB
dask.array<reshape, shape=(1815085, 16, 4), dtype=float32, chunksize=(1048576, 16, 4), chunktype=numpy.ndarray>
Coordinates:
  * time          (time) float64 15MB 18.67 18.67 18.67 ... 79.17 79.17 79.17
  * tetrode       (tetrode) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
  * channel       (channel) int64 32B 0 1 2 3
    tetrode_name  (tetrode, channel) <U4 1kB 'TT1' 'TT1' 'TT1' ... 'TT16' 'TT16'
    channel_name  (tetrode, channel) <U4 1kB 'CH40' 'CH38' ... 'CH30' 'CH32'
Attributes:
    fs:       30000.0
    units:    microvolts

In [27]:
xr_traces = da.values
print(xr_traces.dtype)
xr_traces

float32


array([[ 65.715   ,  62.984997,  61.62    , ..., 147.81    , 158.34    ,
        157.75499 ],
       [ 54.6     ,  58.304996,  56.355   , ..., 143.90999 , 150.54    ,
        146.25    ],
       [ 42.12    ,  54.405   ,  44.655   , ..., 148.59    , 165.555   ,
        164.18999 ],
       ...,
       [-49.335   , -42.315   , -60.059998, ...,  -9.945   ,   3.12    ,
          8.969999],
       [-43.68    , -30.224998, -45.239998, ...,   8.19    ,  10.92    ,
         26.714998],
       [-29.054998, -42.704998, -48.554996, ...,   9.165   ,   7.41    ,
         23.984999]], shape=(1815085, 64), dtype=float32)

In [ ]:
print(
    dict(
        enumerate(OpenEphysBinaryRecordingExtractor.get_available_experiments(ACQ_DIR))
    )
)
print(dict(enumerate((zip(*OpenEphysBinaryRecordingExtractor.get_streams(ACQ_DIR))))))

{0: np.str_('experiment1')}
{0: ('Record Node 101#Acquisition_Board-100.acquisition_board', '0'), 1: ('Record Node 101#Acquisition_Board-100.memory_usage', '1')}


In [43]:
extractor = OpenEphysBinaryRecordingExtractor(
    ACQ_DIR, stream_id="0", load_sync_timestamps=True
)
extractor

OpenEphysBinaryRecordingExtractor: 64 channels - 30.0kHz - 3 segments - 5,411,492 samples 
                                   180.38s (3.01 minutes) - int16 dtype - 660.58 MiB
Segments:
Samples:   1,815,085 | 1,807,473 | 1,788,934
Durations: 60.50s (1.01 minutes) | 60.25s (1.00 minutes) | 59.63s
Memory:    221.57 MiB | 220.64 MiB | 218.38 MiB

In [30]:
si_traces = extractor.get_traces(segment_index=0, return_in_uV=True)
si_traces

array([[ -69.225    ,   34.905    ,   11.8949995, ...,   52.26     ,
          79.365    ,   36.27     ],
       [ -78.78     ,   37.05     ,    5.0699997, ...,   39.       ,
          75.27     ,   25.935    ],
       [-102.96     ,   35.489998 ,   12.48     , ...,   41.535    ,
          81.314995 ,   36.465    ],
       ...,
       [ -46.019997 ,  -18.914999 ,    9.554999 , ...,  -57.524998 ,
         -96.134995 ,  -82.875    ],
       [ -37.635    ,  -32.76     ,   -2.5349998, ...,  -47.19     ,
         -85.604996 ,  -72.54     ],
       [ -28.859999 ,  -21.84     ,   13.259999 , ...,  -39.       ,
         -77.21999  ,  -65.13     ]], shape=(1815085, 64), dtype=float32)

In [31]:
np.array_equal(si_traces[:, [39, 37, 35, 33]], xr_traces[:, :4])

True

In [32]:
np.allclose(si_traces[:, [39, 37, 35, 33]], xr_traces[:, :4])

True

In [33]:
extractor.get_time_info(segment_index=0)

{'sampling_frequency': 30000.0,
 't_start': None,
 'time_vector': array([18.66570046, 18.66573379, 18.66576713, ..., 79.16843379,
        79.16846712, 79.16850045], shape=(1815085,))}

In [34]:
extractor.get_times(segment_index=0)

array([18.66570046, 18.66573379, 18.66576713, ..., 79.16843379,
       79.16846712, 79.16850045], shape=(1815085,))

In [35]:
extractor.has_time_vector(segment_index=0)

True

In [36]:
da.time.values

array([18.66570046, 18.66573379, 18.66576713, ..., 79.16843379,
       79.16846712, 79.16850045], shape=(1815085,))

In [37]:
extractor.select_channels(["CH40", "CH38", "CH36", "CH34"]).get_traces(
    segment_index=0, return_in_uV=True
)

array([[ 65.715   ,  62.984997,  61.62    ,  54.795   ],
       [ 54.6     ,  58.304996,  56.355   ,  49.92    ],
       [ 42.12    ,  54.405   ,  44.655   ,  54.015   ],
       ...,
       [-49.335   , -42.315   , -60.059998, -64.545   ],
       [-43.68    , -30.224998, -45.239998, -48.164997],
       [-29.054998, -42.704998, -48.554996, -38.024998]],
      shape=(1815085, 4), dtype=float32)

## Reflect the channel map and tetrode grouping on the SpikeInterface extractor

The raw `extractor` above is a flat list of 64 channels (`CH1`…`CH64`) with no probe
and no grouping. `ta.attach_tetrode_probegroup` reorders the channels into channel-map
order and attaches a probeinterface `ProbeGroup` (one tetrode per group), giving the
recording a `group` property. The recording can then be split / preprocessed / sorted
per tetrode (see SpikeInterface's *Work with tetrodes* and *Process a recording by
channel group* how-tos), and its tetrode structure matches the `ta` DataArray above.

In [38]:
grouped = ta.attach_tetrode_probegroup(extractor)
grouped

ChannelSliceRecording: 64 channels - 30.0kHz - 3 segments - 5,411,492 samples 
                       180.38s (3.01 minutes) - int16 dtype - 660.58 MiB
Segments:
Samples:   1,815,085 | 1,807,473 | 1,788,934
Durations: 60.50s (1.01 minutes) | 60.25s (1.00 minutes) | 59.63s
Memory:    221.57 MiB | 220.64 MiB | 218.38 MiB

In [39]:
# 0-based tetrode index per channel: [0, 0, 0, 0, 1, 1, 1, 1, ...]
grouped.get_channel_groups()

array([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,
        4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,
        8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12,
       12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15])

In [40]:
by_tt = grouped.split_by("group")
print(f"{len(by_tt)} per-tetrode recordings")
by_tt[0].get_channel_ids()  # TT1 = CH40, CH38, CH36, CH34 (channel-map order)

16 per-tetrode recordings


array(['CH40', 'CH38', 'CH36', 'CH34'], dtype='<U4')

In [41]:
# The extractor grouping now matches the `ta` DataArray's tetrode structure.
da_flat = ta.open_tetrode_dataarray(ACQ_DIR, layout="2d_flat_index")
tt1_from_da = list(da_flat.channel.values[:4])
tt1_from_si = list(map(str, by_tt[0].get_channel_ids()))
print("ta TT1:", tt1_from_da)
print("si TT1:", tt1_from_si)
assert tt1_from_si == tt1_from_da
print("tetrode property:", list(map(str, grouped.get_property("tetrode")[:8])))

ta TT1: [np.str_('CH40'), np.str_('CH38'), np.str_('CH36'), np.str_('CH34')]
si TT1: ['CH40', 'CH38', 'CH36', 'CH34']
tetrode property: ['TT1', 'TT1', 'TT1', 'TT1', 'TT2', 'TT2', 'TT2', 'TT2']
